-- Non-destructive migration for accounts that already have GRANDMA_MONITOR.PUBLIC
-- Run as a role with DDL on the schema. Then deploy CV writers + apply cortex_live_events.sql.

USE DATABASE GRANDMA_MONITOR;
USE SCHEMA PUBLIC;

-- Thumbnail column on existing RAW_OBSERVATIONS (nullable)
ALTER TABLE RAW_OBSERVATIONS
  ADD COLUMN IF NOT EXISTS FRAME_THUMB_BASE64 VARCHAR;

-- Live events feed (Cortex task fills this; one row per OBSERVATION_ID)
CREATE TABLE IF NOT EXISTS LIVE_EVENTS (
    ID VARCHAR(36) PRIMARY KEY DEFAULT UUID_STRING(),

    OBSERVATION_ID VARCHAR(36) NOT NULL UNIQUE,
    PRIMARY_PERSON_ID VARCHAR(50),
    PRIMARY_DISPLAY_NAME VARCHAR(100),

    EVENT_TYPE VARCHAR(30) NOT NULL,
    OBSERVED_AT TIMESTAMP_NTZ NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    MEAL_KIND VARCHAR(20),
    HEADLINE VARCHAR(500),
    SUMMARY VARCHAR,

    CONSTRAINT fk_live_events_observation
        FOREIGN KEY (OBSERVATION_ID)
        REFERENCES RAW_OBSERVATIONS(ID)
);
