-- Create database
CREATE DATABASE IF NOT EXISTS GRANDMA_MONITOR;
USE DATABASE GRANDMA_MONITOR;

-- Create schema
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

-- Create warehouse (XSMALL to conserve credits)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60          -- Suspend after 1 min idle
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

SHOW WAREHOUSES;
SHOW DATABASES;