-- Activity Summary

CREATE OR REPLACE VIEW RECENT_ACTIVITY_SUMMARY AS
SELECT 
    e.ID,
    e.PERSON_ID,
    e.DISPLAY_NAME,
    e.EVENT_TYPE,
    e.EVENT_STARTED_AT,
    e.EVENT_ENDED_AT,
    e.DURATION_MINUTES,
    e.CONFIDENCE,
    e.OBJECTS_CONTEXT,
    e.GENAI_SUMMARY
FROM ACTIVITY_EVENTS e
WHERE e.EVENT_STARTED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
ORDER BY e.EVENT_STARTED_AT DESC
LIMIT 100;


-- Current Status View

CREATE OR REPLACE VIEW CURRENT_STATUS AS
WITH latest_per_person AS (
    SELECT 
        PRIMARY_PERSON_ID,
        PRIMARY_DISPLAY_NAME,
        POSE,
        ACTIVITY,
        MOTION_LEVEL,
        OBSERVED_AT,
        ROW_NUMBER() OVER (PARTITION BY PRIMARY_PERSON_ID ORDER BY OBSERVED_AT DESC) as rn
    FROM RAW_OBSERVATIONS
    WHERE PRIMARY_PERSON_ID IS NOT NULL
      AND OBSERVED_AT >= DATEADD('minute', -30, CURRENT_TIMESTAMP())
)
SELECT 
    PRIMARY_PERSON_ID AS PERSON_ID,
    PRIMARY_DISPLAY_NAME AS DISPLAY_NAME,
    POSE AS CURRENT_POSE,
    ACTIVITY AS CURRENT_ACTIVITY,
    MOTION_LEVEL,
    OBSERVED_AT AS LAST_SEEN_AT,
    DATEDIFF('minute', OBSERVED_AT, CURRENT_TIMESTAMP()) AS MINUTES_AGO
FROM latest_per_person
WHERE rn = 1;

-- Alerts that are not acknowledged yet

CREATE OR REPLACE VIEW PENDING_ALERTS AS
SELECT 
    a.ID,
    a.ALERT_TYPE,
    a.SEVERITY,
    a.QUICK_MESSAGE,
    a.TRIGGERED_AT,
    o.PRIMARY_PERSON_ID,
    o.PRIMARY_DISPLAY_NAME,
    DATEDIFF('minute', a.TRIGGERED_AT, CURRENT_TIMESTAMP()) AS MINUTES_AGO
FROM ALERTS a
LEFT JOIN RAW_OBSERVATIONS o ON a.OBSERVATION_ID = o.ID
WHERE a.ACKNOWLEDGED = FALSE
ORDER BY 
    CASE a.SEVERITY 
        WHEN 'critical' THEN 1 
        WHEN 'warning' THEN 2 
        ELSE 3 
    END,
    a.TRIGGERED_AT DESC;